# Generated by Django 4.1.2 on 2022-10-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='rmgb_img',
            field=models.ImageField(blank=True, upload_to='images_rmbg'),
        ),
    ]
