# Generated by Django 4.1.2 on 2022-10-19 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0002_alter_image_rmgb_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='rmgb_img',
            new_name='rmbg_img',
        ),
    ]
